name: Deployment Workflow
on: push
jobs:
    test-build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install Node
              uses: actions/setup-node@v3
              with:
                node-version: 18
            
            - name: Install Dependencies
              run: npm ci

            - name: Run Lint
              run: npm run lint

            - name: Run Tests
              run: npm run test

            - name: Run Build
              run: npm run build

    deploy:
        needs: test-build
        runs-on: ubuntu-latest
        steps:
            - name: Deploy App
              run: echo "Deploying app..."